### ISSUE TITLE
Invoking funtions lesson has spelling errors

### ISSUE THREAD

**Issue by tensai2bai** [rmotr-curriculum/introduction-to-python-programming#1]
e.g.
# The `len` function
print("Lenght of the string RMOTR:")
lenght_of_rmotr = len('RMOTR')
print(lenght_of_rmotr)

lenght -> length

**Comment by santiagobasulto** [comment]
😛 Thanks, fixing it!

**Comment by santiagobasulto** [comment]
Fixed with #3
