### ISSUE TITLE
Intro guidance is wrong

### ISSUE THREAD

**Issue by tensai2bai** [rmotr-curriculum/introduction-to-python-programming#17]
The Description has "
Then, create two instances:
car1 will be have it's color be blue, _model be Tesla,_ and make be Model S.
car2 will be have it's color be red, _model be Chevy_, and make be Camaro.
"

Following this guidance will fail the tests:
assert car1.make == 'Tesla', "car1's make isn't Tesla"
assert car1.model == 'Model S', "car1's model isn't Model S"

assert car2.make == 'Chevy', "car2's make isn't Chevy"
assert car2.model == 'Camaro', "car2's model isn't Camaro"

Please fix it so that the description and the tests agree on what the model and the make are.

**Comment by santiagobasulto** [comment]
Thanks! Fixed in 5229e75fa3fcbede1ee59f8b0a04c95aec49e800.
