### ISSUE TITLE
Bug in 2nd test case in Getting Started > Concatenate Strings

### ISSUE THREAD

**Issue by darrie53** [rmotr-curriculum/introduction-to-python-programming#20]
Here are the two tests:
 Test With Multiple Strings - RUN TEST
def test_with_multiple_strings():
    assert concatenate_strings('abc', 'def') == 'abcdef'
 Test With Empty String - RUN TEST
def test_with_multiple_strings():
    assert concatenate_strings('abc', 'def') == 'abcdef'
_The second one is not working, and it is basically the same test as the 1st one (Multiple Strings Test). This test is not working, and the course lets you to move further with only 1 of 2 tests passed._
 Report: TOTAL TESTS RUN: 1
 PASSED: 1
 FAILED: –
 duration: 0.01961517333984375

**Steps to reproduce**: log in rmotr learning account, go to Intro to Python > Getting Started > https://learn.rmotr.com/python/introduction-to-programming-with-python/getting-started/concatenate-strings
**Expected result**: there would be only one defined string or no strings defined at all (hence the name: Empty String Test)
**Actual result**: Multiple Strings Test and Empty Strings Test are the same; Empty Strings Test is not running.
![image](https://user-images.githubusercontent.com/31228090/29688218-a4f92a70-8927-11e7-825c-48f915efc464.png)

**Comment by santiagobasulto** [comment]
Thanks! fixed here: https://github.com/rmotr-curriculum/introduction-to-python-programming/commit/fe5074d1ae8f9234afb5fb2dd4aa8c275293f977
