### ISSUE TITLE
Course jumps from Collections/Create a One Element Tuple to Dictionaries

### ISSUE THREAD

**Issue by brianr001** [rmotr-curriculum/introduction-to-python-programming#21]
On the Learn platform, the "Create a One Element Tuple" originally loaded with no empty function definition, instead I had to create it entirely myself, which does not seem to be what was intended.

![image](https://user-images.githubusercontent.com/11297686/29992750-d0e17d96-8f57-11e7-8a2c-dcb198f70d66.png)

Also, upon completion of the "Create a One Element Tuple" and pressing the "Next" button, the course jumps to the Dictionaries in the Advanced Collections part of the course, bypassing the remainder of the Collections course.

**Comment by brianr001** [comment]
Same problem, different location:
When I hit the "Next" button after completing Collections/Search for String, it jumps to the Dictionaries page in the next unit, instead of going to the next exercise.

**Comment by santiagobasulto** [comment]
Thanks Brian, fixed in d9c783edf059979326468e580be35a15475b6cdf. Still investigating issue with next element also reported by @Berelarsenp
