### ISSUE TITLE
Bug in Loops and Collections exercise section

### ISSUE THREAD

**Issue by Berelarsenp** [rmotr-curriculum/introduction-to-python-programming#22]
It happend several times that when hit "**next lesson**" after I submitted a solution of an exercise it takes me to the next section "_Advanced collections_", not to the next exercise. It happend after the "**Create a one element tuple**" and "**Search for string**" exercises particularly. First time I thought I had finished the section :'D

Bye!

**Comment by santiagobasulto** [comment]
Thanks! I've submitted the issue upstream to learn.
