### ISSUE TITLE
Function Arguments issue

### ISSUE THREAD

**Issue by sirpwn4g3** [rmotr-curriculum/introduction-to-python-programming#23]
The instructions for running:
def test_five_times_two():
    assert multiply_by_two(5) == 10

Is terribly unclear.  I've attempted adding this in in multiple locations, editing the preexisting function, but running the test always fails.

tests.py:36: in test_five_times_two
    assert multiply_by_two(5) == 10
E   assert None == 10
E    +  where None = multiply_by_two(5)

**Comment by santiagobasulto** [comment]
We've reviewed the description. Thanks @sirpwn4g3
