### ISSUE TITLE
paragraphs rapidly change width when scrolling

### ISSUE THREAD

**Issue by mostlyghost** [rmotr-curriculum/introduction-to-python-programming#4]
When scrolling down past the header, the paragraph abruptly changes widths (becomes narrower) and makes the text jump around.

I need to have the screen magnification up pretty high, but this also happens when zoomed out and very small.

System:
Firefox 54.0.1
OS X 10.10.5

**Comment by santiagobasulto** [comment]
👍 Thanks Jennifer!

**Comment by santiagobasulto** [comment]
Should be fixed now. Thanks again @mostlyghost.
