### ISSUE TITLE
Off by 1 error 

### ISSUE THREAD

**Issue by z1g1** [rmotr-curriculum/introduction-to-python-programming#5]
Looks like there is an off by 1 error in the unit test 'yhn' is the 1st, 3rd, and 6th character 

def test_with_even_length():
    assert chars_in_even_positions('Python') == 'yhn'

**Comment by Jordan-Gillard** [comment]
Hey Zack, in "Python", y is the 1st character, h is the 3rd, and n is the 5th. P is the zeroith character.

**Comment by santiagobasulto** [comment]
Yes, @Jordan-Gillard, the assignment is 1-indexed.
